services:
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'

  app:
    container_name: app
    build:
      context: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      - mongo
    command: [ "./promptier" ]
